database:
  path: "data/production_container_news.db"

collection:
  months_history: 3
  max_concurrent: 8
  timeout_seconds: 30
  retry_attempts: 3
  delay_between_requests: 0.5

processing:
  auto_categorize: true
  extract_versions: true
  sentiment_analysis: false
  keyword_extraction: true
  remove_duplicates: true

publishing:
  auto_publish_repo: true
  auto_publish_telegram: false
  min_importance_repo: 2
  min_importance_telegram: 4

filters:
  min_content_length: 50
  max_content_length: 10000
  blacklist_domains: []
  required_keywords: []
  excluded_keywords: 
    - "advertisement"
    - "sponsored"
    - "ads"